export { LoginWidget } from "./authWidgets/LoginWidget"
export { RegisterWidget } from "./authWidgets/RegisterWidget"
export { CalendarWidget } from "./calendarWidgets/CalendarWidget"
export { EventListWidget } from "./eventsWidgets/EventListWidget"
export { EventEditWidget } from "./eventsWidgets/EventEditWidget"